// Client-side export helpers: CSV download + printable HTML → PDF via browser print.

function csvEscape(v: unknown): string {
  const s = v === null || v === undefined ? "" : String(v);
  if (/[",\n\r]/.test(s)) return `"${s.replace(/"/g, '""')}"`;
  return s;
}

export function downloadCSV(filename: string, rows: Record<string, unknown>[], columns?: string[]) {
  if (rows.length === 0 && !columns) {
    rows = [{ note: "no data" }];
  }
  const cols = columns ?? Object.keys(rows[0] ?? {});
  const header = cols.map(csvEscape).join(",");
  const body = rows.map((r) => cols.map((c) => csvEscape(r[c])).join(",")).join("\n");
  const blob = new Blob([`${header}\n${body}\n`], { type: "text/csv;charset=utf-8" });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  a.remove();
  setTimeout(() => URL.revokeObjectURL(url), 1000);
}

export interface ReportSection {
  heading: string;
  html: string;
}

export function openPrintReport(opts: {
  title: string;
  subtitle?: string;
  sections: ReportSection[];
}) {
  const w = window.open("", "_blank", "noopener,noreferrer,width=1000,height=800");
  if (!w) return;
  const now = new Date().toISOString().replace("T", " ").slice(0, 16);
  w.document.write(`<!doctype html><html><head><meta charset="utf-8"><title>${escapeHtml(
    opts.title,
  )}</title>
  <style>
    :root { color-scheme: light; }
    * { box-sizing: border-box; }
    html,body { margin:0; padding:0; background:#fff; color:#111; font: 13px/1.5 -apple-system, BlinkMacSystemFont, "Segoe UI", Inter, sans-serif; }
    .wrap { max-width: 900px; margin: 0 auto; padding: 32px; }
    header { border-bottom: 2px solid #111; padding-bottom: 16px; margin-bottom: 24px; }
    header .brand { font-size: 12px; letter-spacing: 0.14em; text-transform: uppercase; color:#666; }
    header h1 { margin: 6px 0 4px; font-size: 24px; }
    header .meta { color:#555; font-size: 12px; }
    section { margin-bottom: 28px; page-break-inside: avoid; }
    section h2 { font-size: 14px; text-transform: uppercase; letter-spacing: 0.08em; color:#111; border-bottom:1px solid #ddd; padding-bottom:6px; margin:0 0 12px; }
    table { width:100%; border-collapse: collapse; font-size: 12px; }
    th, td { text-align:left; padding: 6px 8px; border-bottom:1px solid #eee; vertical-align: top; }
    th { background:#f4f4f5; font-weight:600; }
    .grid { display:grid; grid-template-columns: repeat(4, 1fr); gap:12px; }
    .kpi { border:1px solid #e5e5e5; border-radius: 6px; padding: 10px 12px; }
    .kpi .l { font-size: 10px; text-transform:uppercase; color:#666; letter-spacing:0.08em; }
    .kpi .v { font-size: 20px; font-weight:600; margin-top:4px; font-variant-numeric: tabular-nums; }
    .kpi .s { font-size: 11px; color:#666; margin-top:2px; }
    .tag { display:inline-block; padding:1px 6px; border-radius:4px; font-size:10px; font-weight:600; text-transform:uppercase; letter-spacing:0.06em; border:1px solid #ccc; }
    .tag.allow { color:#0a7c3a; border-color:#0a7c3a; }
    .tag.block { color:#b91c1c; border-color:#b91c1c; }
    .tag.revise { color:#a16207; border-color:#a16207; }
    footer { margin-top: 32px; padding-top: 12px; border-top:1px solid #ddd; font-size:11px; color:#666; }
    @media print { .noprint { display:none } .wrap { padding: 24px } }
    .toolbar { position: sticky; top:0; background:#fafafa; padding:12px; border-bottom:1px solid #ddd; text-align:right; }
    .toolbar button { font: inherit; padding: 6px 14px; border:1px solid #111; background:#111; color:#fff; border-radius:4px; cursor:pointer; }
  </style></head><body>
  <div class="toolbar noprint"><button onclick="window.print()">Print / Save as PDF</button></div>
  <div class="wrap">
    <header>
      <div class="brand">JurisCore AI · Governance Report</div>
      <h1>${escapeHtml(opts.title)}</h1>
      ${opts.subtitle ? `<div class="meta">${escapeHtml(opts.subtitle)}</div>` : ""}
      <div class="meta">Generated ${now} UTC</div>
    </header>
    ${opts.sections.map((s) => `<section><h2>${escapeHtml(s.heading)}</h2>${s.html}</section>`).join("")}
    <footer>Confidential — generated by JurisCore AI. Audit trail available in the immutable ledger.</footer>
  </div>
  <script>setTimeout(function(){ /* ready */ }, 100);</script>
  </body></html>`);
  w.document.close();
}

export function escapeHtml(s: string): string {
  return s.replace(/[&<>"']/g, (c) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#39;" })[c]!);
}

export function kpiCard(label: string, value: string, sub?: string): string {
  return `<div class="kpi"><div class="l">${escapeHtml(label)}</div><div class="v">${escapeHtml(value)}</div>${sub ? `<div class="s">${escapeHtml(sub)}</div>` : ""}</div>`;
}

export function htmlTable(headers: string[], rows: (string | number)[][]): string {
  return `<table><thead><tr>${headers.map((h) => `<th>${escapeHtml(h)}</th>`).join("")}</tr></thead><tbody>${rows
    .map((r) => `<tr>${r.map((c) => `<td>${escapeHtml(String(c))}</td>`).join("")}</tr>`)
    .join("")}</tbody></table>`;
}
